# Generated by Django 5.1.5 on 2025-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.TextField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(default='no_picture.jpg', upload_to='recipes')),
            ],
        ),
    ]
