# Generated by Django 5.1.5 on 2025-01-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.TextField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
